version: "3.8"
name: debates

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - ${MINIO_PATH}:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

  solr:
    build:
      context: ./solr
    ports:
      - "8983:8983"
    networks:
      - debates_network
    healthcheck:
      test: curl --max-time 10 -f http://localhost:8983 || exit 1
      start_period: 60s
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ${SOLR_PATH}:/var/solr
    command:
      - solr-precreate
      - debates
      - /opt/solr/server/solr/configsets/debates

  mongodb:
    image: mongo:7.0.8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    networks:
      - debates_network
    volumes:
      - ${MONGO_PATH}:/data/db

  mongodb-express:
    image: mongo-express:1.0.2-18
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    networks:
      - debates_network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - solr
    networks:
      - debates_network
    environment:
      VITE_SOLR_URL: ${SOLR_SELECT_URL}
      VITE_VIDEO_INPUT: ${VIDEO_INPUT}
      VITE_SUBTITLES_INPUT: ${SUBTITLES_INPUT}
      VITE_MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/
      VITE_MONGO_DB: ${MONGO_DB}
      VITE_MONGO_VIDEO_COLLECTION: ${MONGO_VIDEO_COLLECTION}
    command: ["node", "build"]

  dataloader:
    build:
      context: ./dataloader
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    networks:
      - debates_network
    environment:
      SOLR_URL: ${SOLR_BASE_URL}
      VIDEO_INPUT: ${VIDEO_INPUT}
      SUBTITLES_INPUT: ${SUBTITLES_INPUT}
      MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/
      MONGO_DB: ${MONGO_DB}
      MONGO_VIDEO_COLLECTION: ${MONGO_VIDEO_COLLECTION}
    command: ["/bin/sh"]

  proxy:
    build:
      context: ./proxy
    depends_on:
      solr:
        condition: service_healthy
    networks:
      - debates_network
    ports:
      - "8010:80"

  reverse-proxy:
    image: nginx:alpine
    networks:
      - debates_network
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - type: bind
        source: /etc/letsencrypt/archive/debates.swisscustodian.ch/cert1.pem
        target: /etc/nginx/ssl/debates.swisscustodian.ch.cert
        read_only: true
      - type: bind
        source: /etc/letsencrypt/archive/debates.swisscustodian.ch/privkey1.pem
        target: /etc/nginx/ssl/debates.swisscustodian.ch.key
        read_only: true
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    secrets:
      - htpasswd

secrets:
  htpasswd:
    file: /etc/apache2/.htpasswd

networks:
  debates_network:
    driver: bridge
